apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-service-deploy
spec:
  selector:
    matchLabels:
      service: python-service
  template:
    metadata:
      labels:
        service: python-service
    spec:
      containers:
      - name: python-service
        image: python-service
        ports:
          - containerPort: 8000
