supported_databases = ['postgres']

def db(database=None):
    """
    Create a database pod of the given type.
    """
    objects = ['database-pv:persistentvolume', 'database-pv-claim:persistentvolumeclaim']
    k8s_yaml('volume.yaml')
    k8s_yaml('{}.yaml'.format(database))

    port = None
    if database == 'postgres':
        objects.extend(['database-config:configmap'])
        port = 5432
        k8s_resource('postgress', objects=objects, port_forwards=[port])
    else:
        fail('Unsupported database: {}'.format(database))

if config.main_path == __file__:
    config.define_string('database', usage='Specify database vendor/type to run. Currently supported: {}'.format(supported_databases))
    cfg = config.parse()
    database = cfg.get('database', 'postgres')
    db(database)
